In [1]:
import numpy as np
a = [1,2,3,4]
sum = np.sum(a)
print("Sum of array elements is",sum)
min = np.min(a)
print("Minimum of array elements is",min)
max = np.max(a)
print("Maximum of array elements is",max)
mean = np.mean(a)
print("Mean of array elements is",mean)
med = np.median(a)
print("Median of array elements is",med)
cor = np.corrcoef(a)
print("Correaltion coefficiant of array elements is",cor)
std = np.std(a)
print("standard deviation of array elements is",std)

Sum of array elements is 10
Minimum of array elements is 1
Maximum of array elements is 4
Mean of array elements is 2.5
Median of array elements is 2.5
Correaltion coefficiant of array elements is 1.0
standard deviation of array elements is 1.118033988749895


In [2]:
mat = [[1,2,3,4],[3,5,6,8],[8,9,3,4]]
sum = np.sum(mat)
print("Sum of matrix elements is",sum)
min = np.min(mat)
print("Minimum of the matrix:",min)
max = np.max(mat)
print("Maximum of the matrix:",max)
mean = np.mean(mat)
print("Mean of the matrix:",mean)
med = np.median(a)
print("Median of the matrix:",med)
cor = np.corrcoef(mat)
print("Correaltion coefficiants of the matrix elements:\n",cor)
std = np.std(mat)
print("standard deviation of array elements is",std)

Sum of matrix elements is 56
Minimum of the matrix: 1
Maximum of the matrix: 9
Mean of the matrix: 4.666666666666667
Median of the matrix: 2.5
Correaltion coefficiants of the matrix elements:
 [[ 1.          0.99227788 -0.78935222]
 [ 0.99227788  1.         -0.70710678]
 [-0.78935222 -0.70710678  1.        ]]
standard deviation of array elements is 2.4608038433722337


In [3]:

def sum(a,b):
 return a+b

sum(4,5)

9

In [4]:
def cube(x):
 return x*x*x
cube(4)

64

In [5]:
lambda_cube = lambda y: y*y*y
lambda_cube(5)

125

In [6]:

my_list= [5,7,2,8,6]
my_list_squared = []
for i in my_list:
 i_squared = i**2
 my_list_squared.append(i_squared)
my_list_squared

[25, 49, 4, 64, 36]

In [10]:
list3 = list(map(lambda x:x+4,list1))
list3

NameError: name 'list1' is not defined

In [9]:

set_of_strings = ['abc','def','xyz']
string_map_22 = list(map(lambda my_string: my_string + '_2022', set_of_strings))
string_map_22


['abc_2022', 'def_2022', 'xyz_2022']

In [11]:
def oddeven(x):
 if x%2 == 0:
 return True
 else:
 return False

list1 = [4,5,6,7,8,9]
evenlist = list(filter(oddeven,list1))
evenlist

IndentationError: expected an indented block after 'if' statement on line 2 (1049340749.py, line 3)

In [12]:
list1 = [4,5,6,7,8,9]
evenlist = list(filter(lambda x:True if x%2==0 else False,list1))
evenlist

[4, 6, 8]

In [13]:
from functools import reduce
def sum(x,y):
 return x+y
list1 = [6,7,8,9]
s = reduce(sum,list1)
s

30

In [14]:

x = np.zeros(10)
print(x)
print("Update sixth value to 11")
x[6] = 11
print(x)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Update sixth value to 11
[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


In [15]:
car_names = ['chevrolet', 'buick', 'ply', 'amc', 'ford']
horsepower = [130, 165, 150, 150, 140]
acceleration = [18, 15, 18, 16, 17]
car_hp_acc_arr = np.array([car_names, horsepower, acceleration])
car_hp_acc_arr

array([['chevrolet', 'buick', 'ply', 'amc', 'ford'],
       ['130', '165', '150', '150', '140'],
       ['18', '15', '18', '16', '17']], dtype='<U11')

In [16]:
car_hp_acc_arr[0:2]

array([['chevrolet', 'buick', 'ply', 'amc', 'ford'],
       ['130', '165', '150', '150', '140']], dtype='<U11')

In [17]:
car_hp_acc_arr[0:2, 3:5]

array([['amc', 'ford'],
       ['150', '140']], dtype='<U11')

In [18]:
#creating a list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]
#creating a numpy array from horsepower list
horsepower_arr = np.array(horsepower)
#mean horsepower
print("Mean horsepower = ",np.mean(horsepower_arr))

Mean horsepower =  147.0


In [19]:
#creating a list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]
#creating a numpy array from horsepower list
horsepower_arr = np.array(horsepower)
x = np.where(horsepower_arr >= 150)
print(x) # gives the indices
# With the indices , we can find those values
horsepower_arr[x]

(array([1, 2, 3], dtype=int64),)


array([165, 150, 150])

In [20]:
#creating a list of 5 horsepower values
horsepower = [130, 165, 150, 150, 140]
#creating a numpy array from horsepower list
horsepower_arr = np.array(horsepower)
#creating filter array
x = horsepower_arr > 135
print(x.dtype)
newarr = horsepower_arr[x]
print(x)
print(newarr)

bool
[False  True  True  True  True]
[165 150 150 140]


In [21]:
start = time.process_time()
v1_scaled = np.zeros((1000000, 1))
for i in range(len(v1)):
 v1_scaled[i] = 2 * v1[i]
end = time.process_time()

print("Scaling vector Answer = " + str(v1_scaled))
print("Time taken = " + str(1000*(end - start)) + " ms")

NameError: name 'time' is not defined

In [22]:
start = time.process_time()
v1_scaled = np.zeros((1000000, 1))
v1_scaled = 2 * v1
end = time.process_time()

print("Scaling vector Answer = " + str(v1_scaled))
print("Time taken = " + str(1000*(end - start)) + " ms")

NameError: name 'time' is not defined

In [23]:
start = time.process_time()
answer = np.zeros((1000000, 1))
for i in range(len(v1)):
 answer[i] = v1[i] * v2[i]

end = time.process_time()
print("Element Wise answer = " + str(answer))
print("Time Taken = " + str(1000*(end - start)) + " ms")

NameError: name 'time' is not defined

In [24]:
start = time.process_time()
answer = np.zeros((1000000, 1))
answer = v1 * v2
end = time.process_time()
print("Element Wise answer = " + str(answer))
print("Time Taken = " + str(1000*(end - start)) + " ms")

NameError: name 'time' is not defined

In [25]:
sizes = [10, 100, 1000, 10000, 100000, 1000000, 10000000]
complexity = pd.DataFrame(columns=['sizes', 'for_loop', 'numpy'])
complexity['sizes'] = sizes

NameError: name 'pd' is not defined

In [26]:
import pandas as pd
import numpy as np
marks = {'Chemistry': [67,90,66,32],
 'Physics': [45,92,72,40],
 'Mathematics': [50,87,81,12],
 'English': [19,90,72,68]}
marks_df = pd.DataFrame(marks, index = ['Subodh', 'Ram', 'Abdul', 'John'])
marks_df


Chemistry  Physics  Mathematics  English
Subodh         67       45           50       19
Ram            90       92           87       90
Abdul          66       72           81       72
John           32       40           12       68

In [27]:
marks_df['Total'] = marks_df['Chemistry'] + marks_df['Physics'] + marks_df['Mathematics'] + m
marks_df

NameError: name 'm' is not defined

In [28]:
marks_df.drop(columns = 'Total', inplace = True)
marks_d

KeyError: "['Total'] not found in axis"